### ISSUE TITLE
hi 我QQ298191658，有问题q我

### ISSUE THREAD

**Issue by jackpater** [dadong1993/MyActions#1]
![image](https://user-images.githubusercontent.com/24645106/103206351-9e6df500-4936-11eb-9ae2-f552650e6e82.png)
日志显示已经互助你的种豆了啊？

**Comment by jackpater** [comment]
【京东账号2（jd_42365bbdf47f5）的京东种豆得豆好友互助码】6lkjif4szxpxl2w2yzlombvwaz2cshhuuojplii

开始助力京东账号2 - jd_42365bbdf47f5的好友: mlrdw3aw26j3wzkmddplw2dtidcs5h6576rtvki

开始助力好友: mlrdw3aw26j3wzkmddplw2dtidcs5h6576rtvki
助力结果的code:0
哎呀，今日已为好友助力过了，明天再来哦

开始助力京东账号2 - jd_42365bbdf47f5的好友: ayv6ue6obie3yev2qggxkigjs43h7wlwy7o5jii

开始助力好友: **ayv6ue6obie3yev2qggxkigjs43h7wlwy7o5jii**
助力结果的code:0
哎呀，今日已为好友助力过了，明天再来哦

**Comment by dadong1993** [comment]
@jackpater 我用京东id  JD_小哥BBQ给你助力的你确认下  收到回复我

**Comment by jackpater** [comment]
> @jackpater 我今天用京东id JD_小哥BBQ给你助力的你确认下 收到回复我

OK，收到了。我小号京东名改名为Mi-koo了。

**Comment by jackpater** [comment]
哥们，最近新加了几个助力码，有意互吗？
【京东账号1（*巫仙山的扫地僧*）】 
京喜农场好友互助码】 1eca21401e1b1855c3e209a59f83175d
签到领现金助力码为 eU9YaeW6MKkupT3RnydBhA
口袋书店助力码为 8d3b23136ebc428f936668cdec7264d1

【京东账号2（*mi-koo*）】
京喜农场好友互助码 bb945a53691996522d0dd952fec82ce3
签到领现金助力码为 Ihs-be63Yf4h7G3Wz3cU1g
口袋书店助力码为 6b01426d21d747f88a2cc555b076ddd9

**Comment by jackpater** [comment]
今天作者被删库了，都失效了。

**Comment by dadong1993** [comment]
> 今天作者被删除库了，都失效了。

好几个大佬git账号都注销了  找了几个仓库不太理想  琢磨怎么搞腾讯云呢

**Comment by jackpater** [comment]
> > 今天作者被删除库了，都失效了。
> 
> 好几个大佬git账号都注销了 找了几个仓库不太理想 琢磨怎么搞腾讯云呢

我也在研究，有进展了通知下。@__@

**Comment by dadong1993** [comment]
> > > 今天作者被删除库了，都失效了。
> > 
> > 
> > 好几个大佬git账号都踩了找了几个仓库不太理想琢磨怎么搞腾讯云呢
> 
> 我也在研究，有进展了通知下。@ __ @

函数需要实名认证 同步大佬的数据也可用 我今晚用小号试一试   
我又用git上一位大佬的代码同步了一个 还可以用 不知道明天会啥样
